server:
  port: 8287
  error:
    include-message: always
  max-http-request-header-size: 50KB

spring:
  application:
    name: gestimo_backend_springboot
  profiles:
    default: prod
  main:
    allow-circular-references: true

  mail:
    host: smtp-fr.securemail.pro
    port: 587
    username: info@molibetycenter.com
    password: 2024@Seve2024
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: always

  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
      validation-timeout: 3000
      idle-timeout: 600000

  servlet:
    multipart:
      max-file-size: 528KB
      max-request-size: 528KB

jwt:
  secret: "[a-zA-Z0-9._]^+$GuidelinAurorees8SaisonACfsewwsikkoggishherforAlphabeticalArraNumeralsandOtherSymbo$"

app:
  password-reset-url: http://51.75.142.41/reset-password
  default-user-email: bossohpaulin@gmail.com
  user-security:
    inactivity-disable-days: 30
    inactivity-check-cron: "0 0 2 * * *"
    protected-roles: SUPER_SUPERVISEUR

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when-authorized

info:
  app:
    name: gestimoweb
    description: This is an application to manage employees
    version: "1.0"
