spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/dbgestimoweb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: gestimoweb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

app:
  password-reset-url: http://localhost:4200/reset-password
  cors:
    allowed-origin-patterns: "http://localhost:[*],http://127.0.0.1:[*]"

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.orm.jpa: WARN
    org.springframework.transaction: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.data.auditing: WARN
