
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/dbgestimoweb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: gestimo
    password: gestimoweb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

app:
  password-reset-url: https://gestimoweb.com/reset-password

# FNE Production Configuration (DGI)
# fne:
#   enabled: true
#   base-url: https://www.services.fne.dgi.gouv.ci/ws
#   bearer-token: 01h7neCqBmAqU8lmDy0AcE1ILWAvPhTe

# invoice:
#   api:
#     enabled: true
#     base-url: https://www.services.fne.dgi.gouv.ci/ws
#     token: 01h7neCqBmAqU8lmDy0AcE1ILWAvPhTe
#     sign-path: /external/invoices/sign
  enabled: true
  base-url: http://54.247.95.108/ws
  bearer-token: WCRHegK8Jk5HyNabnYSq1nmozBSj3BCC

invoice:
  api:
    enabled: true
    base-url: http://54.247.95.108/ws
    token: WCRHegK8Jk5HyNabnYSq1nmozBSj3BCC
    sign-path: /external/invoices/sign

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate.SQL: ERROR
