spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgestimoweb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: gestimoweb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

app:
  password-reset-url: http://localhost:4200/reset-password
  cors:
    allowed-origin-patterns: "http://localhost:[*],http://127.0.0.1:[*]"

fne:
  enabled: true
  base-url: http://54.247.95.108/ws
  bearer-token: WCRHegK8Jk5HyNabnYSq1nmozBSj3BCC

invoice:
  api:
    enabled: true
    base-url: http://54.247.95.108/ws
    token: WCRHegK8Jk5HyNabnYSq1nmozBSj3BCC
    sign-path: /external/invoices/sign

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.orm.jpa: WARN
    org.springframework.transaction: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.data.auditing: WARN
