package com.bzdata.gestimospringbackend.Services;

import com.bzdata.gestimospringbackend.DTOs.PrestationAdditionnelReservationSaveOrrUpdate;

public interface PrestationAdditionnelReseravtionService extends AbstractService<PrestationAdditionnelReservationSaveOrrUpdate>{

}
